// <auto-generated />
using System;
using DevelopmentProposalScrapper.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevelopmentProposalScrapper.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260512064657_AddCouncilApplicationNumber")]
    partial class AddCouncilApplicationNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevelopmentProposalScrapper.Domain.Entities.DevelopmentApplication", b =>
                {
                    b.Property<string>("PlanningPortalApplicationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ApplicationStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("ApplicationType")
                        .HasColumnType("integer");

                    b.Property<string>("CouncilApplicationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateLastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DeterminationDate")
                        .HasColumnType("date");

                    b.HasKey("PlanningPortalApplicationNumber");

                    b.ToTable("DevelopmentApplications");
                });

            modelBuilder.Entity("DevelopmentProposalScrapper.Domain.Entities.DevelopmentApplication", b =>
                {
                    b.OwnsMany("DevelopmentProposalScrapper.Infrastructure.External.Models.OnlineDA.Address", "Addresses", b1 =>
                        {
                            b1.Property<string>("DevelopmentApplicationPlanningPortalApplicationNumber")
                                .HasColumnType("character varying(50)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("FullAddress")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Postcode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("State")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("StreetName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("StreetNumber1")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("StreetNumber2")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("StreetNumber3")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("StreetType")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Suburb")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("X")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Y")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("DevelopmentApplicationPlanningPortalApplicationNumber", "Id");

                            b1.ToTable("Address");

                            b1.WithOwner()
                                .HasForeignKey("DevelopmentApplicationPlanningPortalApplicationNumber");

                            b1.OwnsMany("DevelopmentProposalScrapper.Infrastructure.External.Models.OnlineDA.Lot", "Lot", b2 =>
                                {
                                    b2.Property<string>("AddressDevelopmentApplicationPlanningPortalApplicationNumber")
                                        .HasColumnType("character varying(50)");

                                    b2.Property<int>("AddressId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("LotNo")
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasAnnotation("Relational:JsonPropertyName", "Lot");

                                    b2.Property<string>("PlanLabel")
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)");

                                    b2.HasKey("AddressDevelopmentApplicationPlanningPortalApplicationNumber", "AddressId", "Id");

                                    b2.ToTable("Lot");

                                    b2.WithOwner()
                                        .HasForeignKey("AddressDevelopmentApplicationPlanningPortalApplicationNumber", "AddressId");
                                });

                            b1.Navigation("Lot");
                        });

                    b.OwnsOne("DevelopmentProposalScrapper.Infrastructure.External.Models.OnlineDA.CouncilInfo", "Council", b1 =>
                        {
                            b1.Property<string>("DevelopmentApplicationPlanningPortalApplicationNumber")
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("CouncilName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("DevelopmentApplicationPlanningPortalApplicationNumber");

                            b1.ToTable("DevelopmentApplications");

                            b1.WithOwner()
                                .HasForeignKey("DevelopmentApplicationPlanningPortalApplicationNumber");
                        });

                    b.OwnsMany("DevelopmentProposalScrapper.Infrastructure.External.Models.OnlineDA.ProposedDevelopmentType", "ProposedDevelopmentTypes", b1 =>
                        {
                            b1.Property<string>("DevelopmentApplicationPlanningPortalApplicationNumber")
                                .HasColumnType("character varying(50)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("DevelopmentType")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("DevelopmentApplicationPlanningPortalApplicationNumber", "Id");

                            b1.ToTable("ProposedDevelopmentType");

                            b1.WithOwner()
                                .HasForeignKey("DevelopmentApplicationPlanningPortalApplicationNumber");
                        });

                    b.Navigation("Addresses");

                    b.Navigation("Council");

                    b.Navigation("ProposedDevelopmentTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
