services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dGuN2836
      POSTGRES_DB: ArchivalRecording

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:5341"
      - "8080:80"
    volumes:
      - seq_data:/data
    environment:
      ACCEPT_EULA: "Y"

volumes:
  postgres_data:
  seq_data:
